### ISSUE TITLE
OSX 10.12 ISO doesnt have Disk Utilities available when booted

### ISSUE THREAD

**Issue by peterdk** [bradleysepos/osimg#1] opened 2016-12-12 18:22 UTC
I tried to create a bootable ISO with this script for OSX 10.12.
This works, insofar that the installer boots properly. However, the menu option of Disk Utility or TimeMachine restore are not present, even though the installer itselfs refers to it in it's welcome text.

**Comment by bradleysepos** [comment] 2016-12-12 19:25
Thanks for the report.

I recently upgraded one of my magazines to 10.12.1 using a DVD+R DL created from an osimg ISO. No issues using Disk Utility to partition a new SSD.

It will be very helpful if you will provide more information such as the system model, language, and bootable device, and specific build of macOS. Hopefully I can replicate the issue.

**Comment by bradleysepos** [comment] 2016-12-18 19:49
@peterdk Closing for now as I cannot reproduce. If you can provide further information (see previous comment), add a comment and I will be glad to reopen. Cheers.

**Comment by peterdk** [comment] 2016-12-18 19:50
@bradleysepos  sorry, I had indeed no time to track it down. Will try to get to it the coming weeks.

**Comment by peterdk** [comment] 2016-12-18 21:38
Hi, I tried creating a ISO again, and this time it worked almost ok: Disk Utility option was now visible when booted into the ISO. However, restoring from TimeMachine option was not present in the menu, while it was referred to in the installer welcome screen.

sudo ./osimg "/Applications/Install macOS Sierra.app" ~/Desktop/Sierra.iso

macOS 10.12.2 Sierra (16C68)
Creating temporary image...
Copying system packages...
Shrinking image...
Saving final image...
Updating ownership...
Cleaning up...
Done.

**Comment by bradleysepos** [comment] 2016-12-19 23:36
So far, I've found that the Time Machine application is not alongside the other utilities on the installation media. That said, it *does* exist, and you can launch it from Terminal with the following command:

    "/Volumes/OS X Base System/System/Installation/CDIS/Time Machine System Restore.app/Contents/MacOS/Time Machine System Restore"

I have a few more things to test before reporting back.

**Comment by bradleysepos** [comment] 2016-12-22 20:04
I did some additional research:

- The image boots directly into the macOS Installer, which has a Utilities menu but lacks an option related to Time Machine.
- A USB device created using Apple's `createinstallmedia` command boots into macOS Utilities, which presents a dialog containing options to restore from Time Machine, Install macOS, etc. The installer app selected here seems to be different; it has no Utilities menu and no mention of Time Machine is made.

So it would appear that different installer apps are used depending on how the install media is created. The lack of a Time Machine option in the Utilities menu seems to be an oversight on Apple's part and may not have been properly tested before release.

I'll have to do more research to find out which system versions this affects. If possible, I will symlink the Time Machine restoration app in the Utilities menu directory. Otherwise, I will provide instructions for launching it via Terminal as I mentioned before.

**Closed** 2017-03-23 15:46 UTC

**Comment by bradleysepos** [comment] 2017-03-23 15:51
@peterdk After trying to add items to the installer menu (some appeared, some did not), I managed to figure out how to boot directly into macOS Utilities instead of the installer app. Time Machine System Restore is presented as an option directly after selecting a language, same as with images created by Apple's tools.

Thanks for the report and your patience!

**Comment by peterdk** [comment] 2017-03-23 15:52
@bradleysepos Awesome! Thanks for the effort!
